CREATE TABLE IF NOT EXISTS transactions (
    id SERIAL PRIMARY KEY, 
    operation_type VARCHAR(10) NOT NULL,
    amount DECIMAL(10, 2),
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP 
);